### ISSUE TITLE
startAndAwaitEndEvent fails in cojunction with call activities

### ISSUE THREAD

**Issue by robpal94** [process-engine/process_engine#106]
#### Describe your issue
When trying to executing a process which contains a call activity by calling the function `startAndAwaitEndEvent` the following stack trace is thrown: 

```
(node:37327) UnhandledPromiseRejectionWarning: TypeError: this.eventAggregator.subscribeOnce is not a function
    at Promise (/Users/robin/Documents/process_engine/process_engine_meta/process_engine/dist/commonjs/new_model/runtime/engine/execute_process_service.js:64:59)
    at new Promise (<anonymous>)
    at ExecuteProcessService.startAndAwaitEndEvent (/Users/robin/Documents/process_engine/process_engine_meta/process_engine/dist/commonjs/new_model/runtime/engine/execute_process_service.js:62:16)
    at ConsumerApiService._startProcessInstance (/Users/robin/Documents/process_engine/process_engine_meta/_integration_tests/node_modules/@process-engine/consumer_api_core/dist/commonjs/consumer_api.js:188:48)
    at ConsumerApiService.startProcessInstance (/Users/robin/Documents/process_engine/process_engine_meta/_integration_tests/node_modules/@process-engine/consumer_api_core/dist/commonjs/consumer_api.js:57:37)
    at <anonymous>
```

#### Inspection

I've looked a bit into this. 

At the point, where `this.eventAggregator.subscribeOnce();` is called (execute_process_service.ts line 120), the `eventAggregator` only contains an Array with `processDefinition` Objects, but not a `subscribeOnce` Method. 

#### How can others reproduce the issue?
* Create a process with a call activity
* Execute the process using `startAndAwaitEndEvent`

or 

* Run the CallActivity Integration tests

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by robpal94** [comment]
Since this is only happening on the `error_end_event` Branch, Im guessing that I missed some of the new changes.

**Comment by robpal94** [comment]
The problem was indeed, that my local state was outdated.
