### ISSUE TITLE
Error Boundary event test still fails on "should not alter the execution path"

### ISSUE THREAD

**Issue by robpal94** [process-engine/process_engine#79]
#### Describe your issue
Since I think that Christian already tested his solution, I think that this issue is more related to my configuration/machine then for someone else. 

Nonetheless, I want to know whats wrong with my configuration to continue to develop my own tests for the boundary events.

If I run the error boundary event Test, I get the following messages:
```
➜  _integration_tests git:(develop) ✗ npm test

> @process-engine/process_engine_meta_integration_tests@1.0.0 test /Users/robin/Documents/process_engine/process_engine_meta/_integration_tests
> cross-env NODE_ENV=test CONFIG_PATH=config mocha -t 15000 test/*.js --exit

2018-05-04T14:35:03.520Z - warn: [MetadataProvider] Multiple MetadataProvider Registered!! Have you linked a package that has its own metadata-package in its node_modules? Avoid having multiple MetadataProvider instances, as this can mess up metadata-registration!
2018-05-04T14:35:03.714Z - warn: [MetadataProvider] Multiple MetadataProvider Registered!! Have you linked a package that has its own metadata-package in its node_modules? Avoid having multiple MetadataProvider instances, as this can mess up metadata-registration!


  Error Boundary Event -
2018-05-04T14:35:04.540Z - info: [test:bootstrapper] Bootstrapper started.
    1) should not alter the execution path, if the node instance, to which the event is attached, was executed successfully.
Continue normal execution
undefined
Error Boundary Event triggered!
{ message: 'test', errorCode: undefined }
    ✓ should successfully catch the error, alter the execution path and write the result to the token history. (65ms)


  1 passing (2s)
  1 failing

  1) Error Boundary Event -
       should not alter the execution path, if the node instance, to which the event is attached, was executed successfully.:
     AssertionError: expected undefined to exist
      at Context.it (test/error_boundary_event_test.js:32:12)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)



npm ERR! Test failed.  See above for more details.
```
#### What I tried
* Pull the develop branch to my machine
* run the `setup.sh` script on the meta repo

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by robpal94** [comment]
I believe this issue was resolved for me with a `meta exec "git pull"`. So I will close this issue.
